excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ArtsyCarla.github.io
title: Introspection
email: garciapcarla@yahoo.com
author: Carla Garcia
description: My awesome new site
paginate: 4
google_analytics: 